title: SMCA-NOTEBOOK
author: Maria Rosas
email: maryech19@gmail.com
#description:  MCB 5896 - Sequence Based Microbial Community Analysis - University of Connecticut - Fall 2019
#generate social links in footer
#social_links:
   #twitter: '@MariaRo84325291'
   #github:  mhchavez
markdown: kramdown
theme: jekyll-theme-hacker
permalink: /blog/:year/:month/:day/:title

