title: SMCA-NOTEBOOK
author: Maria Rosas
email: maryech19@gmail.com
#description:  MCB 5896 - Sequence Based Microbial Community Analysis - University of Connecticut - Fall 2019
#generate social links in footer
#social_links:
   #twitter: '@MariaRo84325291'
   #github:  mhchavez
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

theme: jekyll-theme-minimal
